[package]
name = "sinc"
version = "0.1.0"
authors = ["modulated <cowkingdom@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sin-rs = { path = ".." }